### ISSUE TITLE
WIndows打包版启动时报错 FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by guimc233** [TransparentLC/xdcmd#5]
system: windows 10 pro x64

log:
```
Traceback (most recent call last):
  File "C:\Users\guimc\Desktop\XDCMD-~1\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\guimc\Desktop\XDCMD-~1\xdnmb\globals.py", line 9, in <module xdnmb.globals>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\guimc\Desktop\XDCMD-~1\xdnmb\action.py", line 2, in <module xdnmb.action>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\guimc\Desktop\XDCMD-~1\xdnmb\api.py", line 10, in <module xdnmb.api>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\guimc\Desktop\XDCMD-~1\xdnmb\util.py", line 2, in <module xdnmb.util>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\guimc\Desktop\XDCMD-~1\chafa\loader.py", line 61, in <module chafa.loader>
  File "C:\Users\guimc\Desktop\XDCMD-~1\chafa\loader.py", line 19, in _get_library_name
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by TransparentLC** [comment]
看了一下，原来使用 chafa.py 还是要额外安装 ImageMagick 来读取图像的，在 Windows 下 chafa.py 会通过查找注册表来确定安装位置然后调用，如果没安装的话就会直接扔出这个报错了。一直没发现这个问题是因为我已经安装了（

总之还是要手动额外安装东西，所以换用 chafa.py 也没方便到哪里去 (　ˇωˇ) 这下得 revert 掉之前的 8ca9d5c 改回使用 subprocess 调用 chafa 的可执行文件的方式了。

**Comment by TransparentLC** [comment]
在 Windows 沙盒里试了一下，应该没问题了……
